name: Publish to Maven

on:
    label:
        types:
          - created

jobs:
    publish:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Java
              uses: actions/setup-java@v4
              with:
                  distribution: 'adopt'
                  java-version: '17'
                #   cache: 'gradle'
                #   cache-dependency-path: |
                #     ./*.gradle.*
                #     ./gradle/wrapper/gradle-wrapper.properties
            - name: Build and Publish to Maven
              run: ./gradle publish
              env:
                  MAVEN_DIR: https://maven.pkg.github.com/DWCarrot/KitPackManager
                  MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
                  MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
                  BUILD_NUMBER: ${{ github.run_number }}
 

